language: python
matrix:
  include:
    - os: linux
      python: 3.4
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: linux
      python: 3.7
    - os: osx
      language: generic
      env: TOXENV=py34
    - os: osx
      language: generic
      env: TOXENV=py35
    - os: osx
      language: generic
      env: TOXENV=py36
    - os: osx
      language: generic
      env: TOXENV=py37
install:
  - pip install .
script:
  - tmhmm -f test.fa
deploy:
  provider: pypi
  user: dansondergaard
  password:
    secure: pkbpjsT030GRHjRvyaQIJVo3sq5YmUI03LlU1HLTFOvPq6qixsxBiWpfCybnhjfVvdRoYdUadcBhelCMkiwucDm2CwPI12wVH7toVZb1AhbNnq+QSILjTlSA+ry7y89XnRTodC9u9SfgA6LvKWs106lcUbZegZCCS6o3j9O7KTI=
  distributions: "sdist bdist_wheel"
  skip_cleanup: true
  on:
    tags: true

