{% set version = 1.2 %}
{% set repo_url = 'https://github.com/dansondergaard/tmhmm.py' %}

package:
  name: tmhmm.py
  version: {{ version }}

source:
  path: ../

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python {{ python }}
    - setuptools
    - numpy {{ numpy }}
    - cython
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  source_files:
    - test.fa
  imports:
    - tmhmm
    - tmhmm.hmm
  commands:
    - tmhmm -f test.fa

about:
  home: {{ repo_url }}
  license: MIT
